26 mudar rst para md
HBN3tw0rk/django-ultratenant pull request #30
Opened 2022-08-03 21:58 UTC by eli-junior

Alterados os arquivos README, CHANGELOG e CONTRIBUTING para o formato Markdown

2022-08-03 22:06 UTC, lucasrcezimbra commented
Vai quebrar os docs: https://github.com/HBN3tw0rk/django-ultratenant/blob/main/docs/readme.rst e https://github.com/HBN3tw0rk/django-ultratenant/blob/main/docs/contributing.rst

2022-08-03 22:45 UTC, andredelorme commented
> Vai quebrar os docs: https://github.com/HBN3tw0rk/django-ultratenant/blob/main/docs/readme.rst e https://github.com/HBN3tw0rk/django-ultratenant/blob/main/docs/contributing.rst

@lucasrcezimbra precisamos desses docs? O que temos no README principal do projeto já não é suficiente no momento?

2022-08-03 22:50 UTC, lucasrcezimbra commented
> @lucasrcezimbra precisamos desses docs? O que temos no README principal do projeto já não é suficiente no momento?

São os docs que vão pro readthedocs. No momento não é necessário, podem ser apagados.

2022-08-03 22:58 UTC, lucasrcezimbra commented
Precisa alterar o `setup.py` adicionando o argumento `long_description_content_type`: https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata

2022-08-03 23:12 UTC, andredelorme reviewed
@eli-junior também acho que podemos remover o docs/ por enquanto.

2022-08-03 23:12 UTC, andredelorme commented on CHANGELOG.md
> +and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
Já sabemos que vamos seguir esses padrões?

2022-08-03 23:12 UTC, andredelorme commented on README.md
> +---
Não parece que essa é a sintaxe correta.

2022-08-03 23:12 UTC, andredelorme commented on README.md
> +        -   url.com/tenant/admin/
A lista parece quebrada.

2022-08-05 01:37 UTC, henriquebastos requested changes
Simplifica os arquivos. Bota tudo no README como uma seção. Fica bem mais fácil nesse começo.

2022-08-25 23:25 UTC, henriquebastos commented
- Remove Contributing e Changelog para seções do README.
- Remove essas refs do loguru
- Tira aquele print pelamordedeus.

2022-08-26 00:50 UTC, merged